
package org.certificatic.ejercicio.biblioteca.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BibliotecaService", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BibliotecaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.certificatic.ejercicio.biblioteca.service.Libro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarLibro", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.RegistrarLibro")
    @ResponseWrapper(localName = "registrarLibroResponse", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.RegistrarLibroResponse")
    public Libro registrarLibro(
        @WebParam(name = "arg0", targetNamespace = "")
        Libro arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.certificatic.ejercicio.biblioteca.service.Libro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarLibros", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.ConsultarLibros")
    @ResponseWrapper(localName = "consultarLibrosResponse", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.ConsultarLibrosResponse")
    public List<Libro> consultarLibros();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borrarLibro", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.BorrarLibro")
    @ResponseWrapper(localName = "borrarLibroResponse", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.BorrarLibroResponse")
    public boolean borrarLibro(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.certificatic.ejercicio.biblioteca.service.Libro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarPorIsbn", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.ConsultarPorIsbn")
    @ResponseWrapper(localName = "consultarPorIsbnResponse", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", className = "org.certificatic.ejercicio.biblioteca.service.ConsultarPorIsbnResponse")
    public Libro consultarPorIsbn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
