
package org.certificatic.ejercicio.biblioteca.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BibliotecaServiceImplService", targetNamespace = "http://service.biblioteca.ejercicio.certificatic.org/", wsdlLocation = "http://miguelvega-ejercicio-soap.herokuapp.com/BibliotecaService?wsdl")
public class BibliotecaServiceImplService
    extends Service
{

    private final static URL BIBLIOTECASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BIBLIOTECASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BIBLIOTECASERVICEIMPLSERVICE_QNAME = new QName("http://service.biblioteca.ejercicio.certificatic.org/", "BibliotecaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://miguelvega-ejercicio-soap.herokuapp.com/BibliotecaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIBLIOTECASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BIBLIOTECASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BibliotecaServiceImplService() {
        super(__getWsdlLocation(), BIBLIOTECASERVICEIMPLSERVICE_QNAME);
    }

    public BibliotecaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIBLIOTECASERVICEIMPLSERVICE_QNAME, features);
    }

    public BibliotecaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BIBLIOTECASERVICEIMPLSERVICE_QNAME);
    }

    public BibliotecaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIBLIOTECASERVICEIMPLSERVICE_QNAME, features);
    }

    public BibliotecaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BibliotecaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BibliotecaService
     */
    @WebEndpoint(name = "BibliotecaServiceImplPort")
    public BibliotecaService getBibliotecaServiceImplPort() {
        return super.getPort(new QName("http://service.biblioteca.ejercicio.certificatic.org/", "BibliotecaServiceImplPort"), BibliotecaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliotecaService
     */
    @WebEndpoint(name = "BibliotecaServiceImplPort")
    public BibliotecaService getBibliotecaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.biblioteca.ejercicio.certificatic.org/", "BibliotecaServiceImplPort"), BibliotecaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIBLIOTECASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BIBLIOTECASERVICEIMPLSERVICE_EXCEPTION;
        }
        return BIBLIOTECASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
